#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2012 OpenWrt.org

START=70
STOP=10
USE_PROCD=1

CONF_FILE='/etc/afp.conf'

start_instance()
{
    local hostname
    local path

    config_get hostname $1 hostname
    config_get path $1 path

    if ! enabled; then
        stop
        exit 0
    fi

    sed -i "/^path =/c\path = $path" $CONF_FILE
    sed -i "/^hostname =/c\hostname = $hostname" $CONF_FILE
}

init_config() {
	config_load netatalk
	config_foreach start_instance netatalk
}

service_triggers() {
	procd_add_reload_trigger "netatalk"
}

start_service()
{
	init_config

	mkdir -p /var/netatalk/CNID/Files
	procd_open_instance
	procd_set_param command /usr/sbin/netatalk -d -F $CONF_FILE
	procd_set_param file $CONF_FILE
	procd_set_param respawn
	procd_close_instance
}
